@ECHO OFF

SET SDL2=FALSE
SET SFML=TRUE
SET NINJA=FALSE
SET CONFIGURATION=Release
SET BUILD_TOOLS=OFF
SET CLEAN=FALSE
SET WINDOWING=SFML
SET RENDERING=SFML
SET NO_APPS=OFF

SET BIN_PATH=..\bin
SET BUILD_PATH=..\Build
SET SOURCE_PATH=..

:PARSE_ARGS
IF NOT "%1" == "" (
	IF /I "%1" == "Debug" SET CONFIGURATION=Debug
	IF /I "%1" == "Tools" SET BUILD_TOOLS=ON
	IF /I "%1" == "SDL2" SET SDL2=TRUE
	IF /I "%1" == "SFML" SET SFML=TRUE
	IF /I "%1" == "NINJA" SET NINJA=TRUE
	IF /I "%1" == "CLEAN" SET CLEAN=TRUE
	IF /I "%1" == "NOAPPS" SET NO_APPS=ON
	SHIFT
	GOTO :PARSE_ARGS
)

IF "%SDL2%" == "TRUE" (
	SET WINDOWING=SDL2
	SET RENDERING=OpenGL
	SET SFML=FALSE
)

IF "%SFML%" == "TRUE" (
	SET WINDOWING=SFML
	SET RENDERING=SFML
	SET SDL2=FALSE
)

IF "%NINJA%" == "TRUE" (
	SET GENERATOR=Ninja
)
